/* Static data for the upgraded site. */

const STATES = [
  { abbr: "AL", name: "Alabama" },
  { abbr: "AK", name: "Alaska" },
  { abbr: "AZ", name: "Arizona" },
  { abbr: "AR", name: "Arkansas" },
  { abbr: "CA", name: "California" },
  { abbr: "CO", name: "Colorado" },
  { abbr: "CT", name: "Connecticut" },
  { abbr: "DE", name: "Delaware" },
  { abbr: "FL", name: "Florida" },
  { abbr: "GA", name: "Georgia" },
  { abbr: "HI", name: "Hawaii" },
  { abbr: "ID", name: "Idaho" },
  { abbr: "IL", name: "Illinois" },
  { abbr: "IN", name: "Indiana" },
  { abbr: "IA", name: "Iowa" },
  { abbr: "KS", name: "Kansas" },
  { abbr: "KY", name: "Kentucky" },
  { abbr: "LA", name: "Louisiana" },
  { abbr: "ME", name: "Maine" },
  { abbr: "MD", name: "Maryland" },
  { abbr: "MA", name: "Massachusetts" },
  { abbr: "MI", name: "Michigan" },
  { abbr: "MN", name: "Minnesota" },
  { abbr: "MS", name: "Mississippi" },
  { abbr: "MO", name: "Missouri" },
  { abbr: "MT", name: "Montana" },
  { abbr: "NE", name: "Nebraska" },
  { abbr: "NV", name: "Nevada" },
  { abbr: "NH", name: "New Hampshire" },
  { abbr: "NJ", name: "New Jersey" },
  { abbr: "NM", name: "New Mexico" },
  { abbr: "NY", name: "New York" },
  { abbr: "NC", name: "North Carolina" },
  { abbr: "ND", name: "North Dakota" },
  { abbr: "OH", name: "Ohio" },
  { abbr: "OK", name: "Oklahoma" },
  { abbr: "OR", name: "Oregon" },
  { abbr: "PA", name: "Pennsylvania" },
  { abbr: "RI", name: "Rhode Island" },
  { abbr: "SC", name: "South Carolina" },
  { abbr: "SD", name: "South Dakota" },
  { abbr: "TN", name: "Tennessee" },
  { abbr: "TX", name: "Texas" },
  { abbr: "UT", name: "Utah" },
  { abbr: "VT", name: "Vermont" },
  { abbr: "VA", name: "Virginia" },
  { abbr: "WA", name: "Washington" },
  { abbr: "WV", name: "West Virginia" },
  { abbr: "WI", name: "Wisconsin" },
  { abbr: "WY", name: "Wyoming" },
];

const QUIZ = [
  { q: "How many stars are on the U.S. flag?", options: ["48", "50", "52", "13"], answer: 1 },
  { q: "Which document declared independence from Britain in 1776?", options: ["The Constitution", "The Declaration of Independence", "The Bill of Rights", "The Emancipation Proclamation"], answer: 1 },
  { q: "What is the national bird of the United States?", options: ["American Robin", "Turkey", "Bald Eagle", "Peregrine Falcon"], answer: 2 },
  { q: "Who was the first President of the United States?", options: ["Thomas Jefferson", "John Adams", "Benjamin Franklin", "George Washington"], answer: 3 },
  { q: "How many stripes are on the U.S. flag?", options: ["13", "15", "50", "7"], answer: 0 },
  { q: "Which state is the largest by area?", options: ["Texas", "California", "Montana", "Alaska"], answer: 3 },
  { q: "What is the national anthem called?", options: ["America the Beautiful", "God Bless America", "The Star-Spangled Banner", "Yankee Doodle"], answer: 2 },
  { q: "In which state is Mount Rushmore located?", options: ["Wyoming", "South Dakota", "Colorado", "Montana"], answer: 1 },
  { q: "Which is the smallest U.S. state?", options: ["Delaware", "Vermont", "Rhode Island", "Connecticut"], answer: 2 },
  { q: "What year did the United States declare independence?", options: ["1776", "1789", "1812", "1492"], answer: 0 },
  { q: "The Statue of Liberty was a gift from which country?", options: ["England", "Spain", "France", "Italy"], answer: 2 },
  { q: "Which U.S. city is known as 'The Big Apple'?", options: ["Los Angeles", "Chicago", "Miami", "New York City"], answer: 3 },
  { q: "What is the official motto of the United States?", options: ["In God We Trust", "E Pluribus Unum", "Semper Fi", "Don't Tread on Me"], answer: 1 },
  { q: "Which river is the longest in the United States?", options: ["Mississippi", "Missouri", "Colorado", "Ohio"], answer: 1 },
];

const ACHIEVEMENTS = [
  { id: "first-firework", icon: "🎆", name: "Ignition", desc: "Launch your first firework." },
  { id: "eagle-mode", icon: "🦅", name: "Eagle Enthusiast", desc: "Turn on Eagle Mode." },
  { id: "full-freedom", icon: "🇺🇸", name: "Full Constitution", desc: "Reach 100% freedom." },
  { id: "all-states", icon: "🏆", name: "Fifty & Fabulous", desc: "Visit all 50 states." },
  { id: "hotdog-50", icon: "🌭", name: "Competitive Eater", desc: "Eat 50+ hot dogs in one contest." },
  { id: "quiz-perfect", icon: "🎓", name: "Mensa Eagle", desc: "Score a perfect quiz." },
  { id: "grill-perfect", icon: "🍔", name: "Platinum Grill", desc: "Serve a perfect plate." },
  { id: "feed-10", icon: "🐣", name: "Eagle Parent", desc: "Feed the pet eagle 10 times." },
  { id: "rocket-launch", icon: "🚀", name: "Space Force", desc: "Launch the Freedom Rocket." },
];
